first version
ozonmp/edu-task-api pull request #2
Opened 2021-11-01 09:22 UTC by Format-C-eft

2021-11-02 16:43 UTC, grozauf requested changes

2021-11-02 16:43 UTC, grozauf commented on api/ozonmp/edu_task_api/v1/edu_task_api.proto
> +      post:"/api/v1/create"
Обычно ручки имеют следующего вида контракты:
POST /api/v1/tasks - создание таска
GET /api/v1/tasks - вывод списка тасков
GET /api/v1/tasks/{id} - вывод таска по id
DELETE /api/v1/tasks/{id} - удаление таска по id
PUT /api/v1/tasks/{id} - апдейт таска по id

2021-11-02 18:18 UTC, Format-C-eft commented on api/ozonmp/edu_task_api/v1/edu_task_api.proto
> +      get:"/api/v1/list/{taskId}/{count}"
Исправлено

2021-11-02 18:18 UTC, Format-C-eft commented on api/ozonmp/edu_task_api/v1/edu_task_api.proto
> +                              lte: 10,
Исправлено

2021-11-02 18:19 UTC, Format-C-eft commented on api/ozonmp/edu_task_api/v1/edu_task_api.proto
> +                              pattern:   "^[A-Za-zА-Яа-я0-9 ]+$",
Исправлено

2021-11-02 18:19 UTC, Format-C-eft commented on api/ozonmp/edu_task_api/v1/edu_task_api.proto
> +                              pattern:   "^[A-Za-zА-Яа-я0-9 ]+$",
Исправлено

2021-11-02 18:20 UTC, Format-C-eft commented on api/ozonmp/edu_task_api/v1/edu_task_api.proto
> +                        lte: 50,
Так как изменено по замечанию другому, теперь этих параметров более нет.

2021-11-02 18:23 UTC, Format-C-eft commented on internal/api/api.go
> +	return &eduTaskAPI{
Исправил, хотя для меня так не очень привычно.

2021-11-02 18:28 UTC, Format-C-eft commented on internal/api/api_create_task.go
> +	err := o.repo.Create(ctx, task)
такое показывали на воркшопе. Как по мне, я согласен что так не прозрачно. Изменил на прозрачное поведение.

2021-11-02 18:29 UTC, Format-C-eft commented on internal/api/api_remove_task.go
> +	if _, err := o.repo.Describe(ctx, taskId); err != nil {
Исправлено.

2021-11-02 18:35 UTC, Format-C-eft commented on internal/api/api_test.go
> +	t.Run("Describe eerror arguments", func(t *testing.T) {
:-) Исправил

2021-11-02 18:49 UTC, Format-C-eft commented on internal/api/api_test.go
> +		DoAndReturn(
Для меня пока так нагляднее, что выполняется и что возвращается.

2021-11-02 18:50 UTC, Format-C-eft commented on internal/api/api_test.http
> +
Для быстрого тестирования REST - я давно использую плагин к vsCode - https://marketplace.visualstudio.com/items?itemName=humao.rest-client

2021-11-02 18:51 UTC, Format-C-eft commented on internal/model/template.go
> +package model
Удален.

2021-11-02 18:56 UTC, Format-C-eft commented on api/ozonmp/edu_task_api/v1/edu_task_api.proto
> +      post:"/api/v1/create"
Принял к сведению, исправил.

2021-11-02 18:58 UTC, Format-C-eft commented on internal/api/api_test.go
> +			}).AnyTimes()
Изменил, на Times()

2021-11-02 19:00 UTC, Format-C-eft commented on docker-compose.yaml
> +      - 8082:8082 # gRPC
Спасибо, просмотрел. Исправлено.

2021-11-02 19:02 UTC, Format-C-eft commented on internal/api/api_remove_task.go
> +	err := o.repo.Remove(ctx, taskId)
Посмотрел на первую домашку там тоже bool & error. С error как то привычнее что ли.

2021-11-04 09:56 UTC, grozauf approved these changes

2021-11-04 09:56 UTC, grozauf commented on internal/api/api.go
> +func NewTaskAPI(r repo.Repo) pb.TaskApiServiceServer { return &eduTaskAPI{repo: r} }
Ну, уж до крайностей можно не доводить -)

2021-11-04 09:56 UTC, grozauf commented on internal/api/api_remove_task.go
> +	err := o.repo.Remove(ctx, req.GetId())
Если оставить только ошибку, то разделение ситуации найден\не найден при удалении придётся делать через ошибку.

2021-11-04 16:00 UTC, Format-C-eft commented on internal/api/api.go
> +func NewTaskAPI(r repo.Repo) pb.TaskApiServiceServer { return &eduTaskAPI{repo: r} }
ну да немного перестарался

2021-11-04 16:25 UTC, merged