Feature/task 4
ozonmp/edu-task-api pull request #3
Opened 2021-11-09 09:19 UTC by Format-C-eft

2021-11-10 12:57 UTC, grozauf requested changes

2021-11-10 12:57 UTC, grozauf commented on internal/app/repo/repo.go
> +		ok, err := database.AcquireTryLock(ctx, tx, 1, v.ID) //nolint
Здесь и ниже. Блокировка на уровне строк - это что-то слишком. Можно выбрать нужный уровень сериализации. Этого, думаю, будет достаточно.

2021-11-10 12:57 UTC, grozauf commented on internal/app/repo/repo.go
> +	var tasks []education.TaskEvent
скорее - events

2021-11-10 12:57 UTC, grozauf commented on internal/app/repo/repo.go
> +	query, args, err = sbu.ToSql()
зачем? sbu.ExecContext() есть. RunWith() надо только указать

2021-11-10 12:57 UTC, grozauf commented on internal/repo/repo.go
> +	pbTaskEvent := pb.TaskEvent{
Мне кажется, что маршалинг надо делать на уровне RepoEvent

2021-11-10 12:57 UTC, grozauf commented on internal/app/repo/repo.go
> +		ok, err := database.AcquireTryLock(ctx, tx, 1, v) //nolint
не нужно

2021-11-10 12:57 UTC, grozauf commented on internal/app/sender/sender.go
> +	log.Debug().Msg("Proto is created")
можно пока что выводить в консоль то, что получилось в taskEvent

2021-11-10 12:57 UTC, grozauf commented on internal/model/education/task.go
> +	_ eventType = iota
Для чего пропускается нулевое значение?

2021-11-10 12:57 UTC, grozauf commented on internal/repo/repo.go
> +		event:     re.NewEventRepo(db),
Такие штуки лучше делать вне конструктора и передавать в конструктор уже созданный объект (указатель на объект). Т.к. если этого не делать, то будет сложно замокать event, если понадобится написать тесты

2021-11-10 12:57 UTC, grozauf commented on internal/repo/repo.go
> +		ToSql()
Как писал выше - не нужно преобразовывать в SQL. squirrel вполне может выполнять запросы к БД

2021-11-10 12:57 UTC, grozauf commented on internal/repo/repo.go
> +		Limit(1).
а может быть больше 1 в результате?

2021-11-10 12:57 UTC, grozauf commented on migrations/00001_init_db.sql
> +    created timestamp default now() NOT NULL,
created_at, updated_at

2021-11-10 12:57 UTC, grozauf commented on migrations/00001_init_db.sql
> +    updated timestamp default now() NOT NULL,
updated_at

2021-11-10 12:57 UTC, grozauf commented on config.yml
> +  host: server1clinux
Нету такого в докере

2021-11-10 13:54 UTC, Format-C-eft commented on internal/app/repo/repo.go
> +var _ EventRepo = &repo{}
На лекциях и воркшопах показывали этот прием, что бы на была подсветка ошибки если более структура не соответствует интерфейсу, а так же проект не соберется.

2021-11-10 18:39 UTC, Format-C-eft commented on internal/app/repo/repo.go
> +		LeftJoin("task_events as tep on tec.task_id = tec.task_id and tec.status = 2").
Это условие соединения в левой части берем все во второй только в обработке, а в конечной выборке берем только тех у кого нет ничего по соединению. тем самым мы отбрасываем из выборки те сущности которые на данный момент обрабатываются кем-то.

2021-11-10 18:44 UTC, Format-C-eft commented on internal/app/repo/repo.go
> +	var tasks []education.TaskEvent
Нет, тут как раз правильно у нас в строке БД находится Event а внутри Event уже Proto Message.

2021-11-10 19:08 UTC, Format-C-eft commented on internal/model/education/task.go
> +	_ eventType = iota
Говорилось на лекции, что в желательно пропускать значения с 0-лем дабы исключить ошибку интерпретации пустого значения в значение переменной.

2021-11-10 19:13 UTC, Format-C-eft commented on internal/repo/repo.go
> +		event:     re.NewEventRepo(db),
Исправлено

2021-11-10 19:14 UTC, Format-C-eft commented on internal/repo/repo.go
> +		Limit(1).
По идее это ключ, значит не может быть. Но привычка "на всякий случай" пока есть.
Исправлено.

2021-11-10 19:20 UTC, Format-C-eft commented on migrations/00001_init_db.sql
> +    created timestamp default now() NOT NULL,
Исправлено

2021-11-10 19:20 UTC, Format-C-eft commented on migrations/00001_init_db.sql
> +    updated timestamp default now() NOT NULL,
Исправлено

2021-11-10 19:20 UTC, Format-C-eft commented on config.yml
> +  host: server1clinux
:-) да нет. забыл перед коммитов изменить. Исправлено

2021-11-10 19:25 UTC, Format-C-eft commented on internal/app/sender/sender.go
> +	log.Debug().Msg("Proto is created")
Не до конца понятно, вывести сериализованный Proto как json ? Или в каком виде?

2021-11-10 19:26 UTC, Format-C-eft commented on internal/app/repo/repo.go
> +		ok, err := database.AcquireTryLock(ctx, tx, 1, v) //nolint
Исправлено

2021-11-10 19:26 UTC, Format-C-eft commented on internal/app/repo/repo.go
> +	query, args, err = sbu.ToSql()
Спасибо, исправлено.

2021-11-11 04:58 UTC, Format-C-eft commented on internal/repo/repo.go
> +		ToSql()
Исправлено

2021-11-11 05:42 UTC, Format-C-eft commented on internal/repo/repo.go
> +	pbTaskEvent := pb.TaskEvent{
Перенес

2021-11-12 11:51 UTC, grozauf commented on internal/app/repo/repo.go
> +		LeftJoin("task_events as tep on tec.task_id = tec.task_id and tec.status = 2").
А условие tec.task_id = tec.task_id для чего? Оно же всегда true, может tec и tep надо?

2021-11-12 11:52 UTC, grozauf commented on internal/app/repo/repo.go
> +	var tasks []education.TaskEvent
эм, массив таск евентов называется таски?

2021-11-13 12:55 UTC, merged