Feature/task 6
ozonmp/edu-task-api pull request #5
Opened 2021-11-23 06:45 UTC by Format-C-eft

Задание VI
1. Имплементировать отправку событий в kafka топик - сделано  с отправкой в пулу брокеров

2. Имплементировать для сервиса {domain-kw}-{subdomain}-facade чтение данных из kafka топика в стандартный поток вывода - Сделано с уровнем легирования debug

3. Имплементировать update операцию - она уже была реализована

4. Имплементировать сохранение прочтенных данных в базу 💎 - сделано, добавлен новый контейнер с постгрей

5. Добавить поддержку работы с множеством брокеров 💎 - по идее реализовано, так как подняты 3-ри брокера.

2021-11-24 18:30 UTC, grozauf requested changes

2021-11-24 18:30 UTC, grozauf commented on cmd/task-facade/main.go
> +		FN:     facade.HandlEventsFacade,
Как то странно хранить в конфиге функцию. Без этого точно нельзя?

2021-11-24 18:30 UTC, grozauf commented on internal/app/kafka/kafka_read.go
> +	return nil
как я понимаю, функция никогда не возвращает ошибку. может ей не нужен возвращаемый аргумент?

2021-11-24 18:30 UTC, grozauf commented on internal/facade/facade.go
> +		cancelFunc: config.Cancel,
в конфиге ещё и функция завершения лежит. Зачем? 
+ при вызове facade.Stop() он завершит тот контекст, к которому принадлежит эта функция. А этот контекст даже не создавался фасадом. Как-то это странно.

2021-11-24 18:31 UTC, grozauf commented on docker-compose.yaml
> +    # command: sh -c "((sleep 15 && kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 2 --partitions 3 --topic edu-task-events)&) && /etc/confluent/docker/run"
Закоменчено?

2021-11-25 08:02 UTC, Format-C-eft commented on cmd/task-facade/main.go
> +		FN:     facade.HandlEventsFacade,
Исправлено

2021-11-25 08:02 UTC, Format-C-eft commented on internal/app/kafka/kafka_read.go
> +	return nil
Да согласен, исправлено

2021-11-25 10:22 UTC, Format-C-eft commented on docker-compose.yaml
> +    # command: sh -c "((sleep 15 && kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 2 --partitions 3 --topic edu-task-events)&) && /etc/confluent/docker/run"
Да это закоментировано. Переделал зависимости запуска брокеров, что бы сначала поднимались 2 и 3 брокер, потом поднимался 1 и он как раз создает топик и его делит на три партиции.

2021-11-29 05:14 UTC, merged